# Generated by Django 4.2 on 2023-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daisy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
