# Generated by Django 4.2 on 2023-04-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daisy', '0002_office_number_alter_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='office',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
