# Generated by Django 4.2 on 2023-04-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daisy', '0003_alter_appointment_phone_number_alter_office_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.TextField(max_length=200),
        ),
    ]
