# Generated by Django 4.2 on 2023-04-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daisy', '0004_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.TextField(max_length=1000),
        ),
    ]
